"""
Team registry keyed by FIFA TLA code (same codes used by football-data.org v4).
"""
TEAMS = {
    "MEX": "🇲🇽 México",
    "RSA": "🇿🇦 África do Sul",
    "KOR": "🇰🇷 Coreia do Sul",
    "CZE": "🇨🇿 Tchéquia",
    "CAN": "🇨🇦 Canadá",
    "SUI": "🇨🇭 Suíça",
    "QAT": "🇶🇦 Catar",
    "BIH": "🇧🇦 Bósnia",
    "BRA": "🇧🇷 Brasil",
    "MAR": "🇲🇦 Marrocos",
    "HAI": "🇭🇹 Haiti",
    "SCO": "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Escócia",
    "USA": "🇺🇸 Estados Unidos",
    "PAR": "🇵🇾 Paraguai",
    "TUR": "🇹🇷 Turquia",
    "AUS": "🇦🇺 Austrália",
    "GER": "🇩🇪 Alemanha",
    "CIV": "🇨🇮 Costa do Marfim",
    "ECU": "🇪🇨 Equador",
    "CUW": "🇨🇼 Curaçao",
    "NED": "🇳🇱 Holanda",
    "SWE": "🇸🇪 Suécia",
    "TUN": "🇹🇳 Tunísia",
    "JPN": "🇯🇵 Japão",
    "BEL": "🇧🇪 Bélgica",
    "EGY": "🇪🇬 Egito",
    "IRN": "🇮🇷 Irã",
    "NZL": "🇳🇿 Nova Zelândia",
    "ESP": "🇪🇸 Espanha",
    "CPV": "🇨🇻 Cabo Verde",
    "KSA": "🇸🇦 Arábia Saudita",
    "URY": "🇺🇾 Uruguai",
    "FRA": "🇫🇷 França",
    "SEN": "🇸🇳 Senegal",
    "IRQ": "🇮🇶 Iraque",
    "NOR": "🇳🇴 Noruega",
    "ARG": "🇦🇷 Argentina",
    "ALG": "🇩🇿 Argélia",
    "AUT": "🇦🇹 Áustria",
    "JOR": "🇯🇴 Jordânia",
    "POR": "🇵🇹 Portugal",
    "COD": "🇨🇩 RD Congo",
    "UZB": "🇺🇿 Uzbequistão",
    "COL": "🇨🇴 Colômbia",
    "ENG": "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Inglaterra",
    "CRO": "🇭🇷 Croácia",
    "GHA": "🇬🇭 Gana",
    "PAN": "🇵🇦 Panamá",
}
