"""add external_id to matches

Revision ID: ec9f0e23c909
Revises: 6554bccea3f8
Create Date: 2026-06-11 19:07:44.042992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec9f0e23c909'
down_revision: Union[str, None] = '6554bccea3f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('external_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'matches', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='unique')
    op.drop_column('matches', 'external_id')
    # ### end Alembic commands ###
